// <auto-generated />
using System;
using Datateal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datateal.Data.Migrations
{
    [DbContext(typeof(DatatealDbContext))]
    [Migration("20260613105702_AddWorkspaces")]
    partial class AddWorkspaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datateal.Core.Catalogs.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccessibleFromAllWorkspaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Catalogs");

                    b.HasDiscriminator<string>("CatalogType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Datateal.Core.Catalogs.CatalogWorkspaceAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("CatalogId", "WorkspaceId")
                        .IsUnique();

                    b.ToTable("CatalogWorkspaceAccess");
                });

            modelBuilder.Entity("Datateal.Core.Environment.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("Datateal.Core.Environment.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("Datateal.Core.RuntimePackages.WheelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("WheelPackages");
                });

            modelBuilder.Entity("Datateal.Core.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasAllCatalogAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Datateal.Core.Users.UserCatalogAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId", "CatalogId")
                        .IsUnique();

                    b.ToTable("UserCatalogAccess");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.WorkspaceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogNames")
                        .HasColumnType("jsonb");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("WorkspaceId", "Title")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceItems_Workspace_Title_Root")
                        .HasFilter("\"FolderId\" IS NULL");

                    b.HasIndex("WorkspaceId", "Title", "FolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceItems_Workspace_Title_FolderId")
                        .HasFilter("\"FolderId\" IS NOT NULL");

                    b.ToTable("WorkspaceItems");

                    b.HasDiscriminator<string>("ItemType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Datateal.Core.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_Workspaces_IsDefault")
                        .HasFilter("\"IsDefault\"");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Datateal.Core.Workspaces.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentRuns")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobParameters");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTaskRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ParentRunId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSchedules");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<TimeSpan>("RetryInterval")
                        .HasColumnType("interval");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeSpan?>("Timeout")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Name")
                        .IsUnique();

                    b.ToTable("JobTasks");

                    b.HasDiscriminator<string>("TaskType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.NodePoolConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentVariableIds")
                        .HasColumnType("jsonb");

                    b.Property<TimeSpan?>("KernelIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<string>("KernelRequirements")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeSpan?>("NodeIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SecretIds")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VmSize")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WheelPackageIds")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("NodePoolConfigs");

                    b.HasDiscriminator<string>("PoolType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRuns");

                    b.HasDiscriminator<string>("TaskType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Datateal.Core.Catalogs.ManagedCatalog", b =>
                {
                    b.HasBaseType("Datateal.Core.Catalogs.Catalog");

                    b.HasDiscriminator().HasValue("Managed");
                });

            modelBuilder.Entity("Datateal.Core.Catalogs.UnmanagedCatalog", b =>
                {
                    b.HasBaseType("Datateal.Core.Catalogs.Catalog");

                    b.Property<string>("CatalogDatabase")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CatalogHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CatalogPort")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EncryptedCatalogPassword")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedStorageConnectionString")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Unmanaged");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.Notebook", b =>
                {
                    b.HasBaseType("Datateal.Core.Workspace.WorkspaceItem");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.Query", b =>
                {
                    b.HasBaseType("Datateal.Core.Workspace.WorkspaceItem");

                    b.Property<double?>("LastDurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastResultJson")
                        .HasColumnType("text");

                    b.Property<string>("LastResultStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasDiscriminator().HasValue("Query");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.NotebookTask", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.SqlQueryTask", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("NodePoolRef")
                                .HasColumnName("SqlQueryTask_NodePoolRef");

                            t.Property("Parameters")
                                .HasColumnName("SqlQueryTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SqlQuery");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.SubJobTask", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SubJobId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("Parameters")
                                .HasColumnName("SubJobTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SubJob");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.InteractiveNodePoolConfig", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.NodePoolConfig");

                    b.HasDiscriminator().HasValue("Interactive");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobNodePoolConfig", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.NodePoolConfig");

                    b.Property<int?>("MaxNodes")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("NodeAcquireTimeout")
                        .HasColumnType("interval");

                    b.Property<int>("WarmNodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasDiscriminator().HasValue("Job");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.NotebookTaskRun", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.TaskRun");

                    b.Property<string>("KernelId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("NodeName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.SqlQueryTaskRun", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.TaskRun");

                    b.Property<string>("KernelId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("NodeName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("SqlQuery");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.SubJobTaskRun", b =>
                {
                    b.HasBaseType("Datateal.Orchestrator.Core.Entities.TaskRun");

                    b.HasDiscriminator().HasValue("SubJob");
                });

            modelBuilder.Entity("Datateal.Core.Catalogs.CatalogWorkspaceAccess", b =>
                {
                    b.HasOne("Datateal.Core.Catalogs.Catalog", "Catalog")
                        .WithMany("WorkspaceAccessList")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datateal.Core.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Datateal.Core.Environment.EnvironmentVariable", b =>
                {
                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datateal.Core.Environment.Secret", b =>
                {
                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datateal.Core.RuntimePackages.WheelPackage", b =>
                {
                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datateal.Core.Users.UserCatalogAccess", b =>
                {
                    b.HasOne("Datateal.Core.Catalogs.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datateal.Core.Users.AppUser", "User")
                        .WithMany("CatalogAccessList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.Folder", b =>
                {
                    b.HasOne("Datateal.Core.Workspace.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.WorkspaceItem", b =>
                {
                    b.HasOne("Datateal.Core.Workspace.Folder", "Folder")
                        .WithMany("Items")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Datateal.Core.Workspaces.WorkspaceMembership", b =>
                {
                    b.HasOne("Datateal.Core.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datateal.Core.Workspaces.Workspace", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.Job", b =>
                {
                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Datateal.Orchestrator.Core.Entities.JobRun", "ParentRun")
                        .WithMany()
                        .HasForeignKey("ParentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("ParentRun");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Schedules")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.NodePoolConfig", b =>
                {
                    b.HasOne("Datateal.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.JobTask", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datateal.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.HasOne("Datateal.Orchestrator.Core.Entities.JobRun", "JobRun")
                        .WithMany("TaskRuns")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datateal.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Datateal.Core.Catalogs.Catalog", b =>
                {
                    b.Navigation("WorkspaceAccessList");
                });

            modelBuilder.Entity("Datateal.Core.Users.AppUser", b =>
                {
                    b.Navigation("CatalogAccessList");
                });

            modelBuilder.Entity("Datateal.Core.Workspace.Folder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Datateal.Core.Workspaces.Workspace", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Navigation("TaskRuns");
                });

            modelBuilder.Entity("Datateal.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
