<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Datateal.Core\Datateal.Core.csproj" />
    <ProjectReference Include="..\..\..\shared\Datateal.Deployment\Datateal.Deployment.csproj" />
  </ItemGroup>

</Project>
