<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datateal.Ui.Server.Core\Datateal.Ui.Server.Core.csproj" />
    <ProjectReference Include="..\Datateal.Ui.Server.Application\Datateal.Ui.Server.Application.csproj" />
    <ProjectReference Include="..\..\Datateal.Ui.Shared\Datateal.Ui.Shared.csproj" />
    <ProjectReference Include="..\..\..\shared\Datateal.Auth\Datateal.Auth.csproj" />
    <ProjectReference Include="..\..\..\shared\Datateal.Data\Datateal.Data.csproj" />
  </ItemGroup>

</Project>
