// <auto-generated />
using System;
using DuckHouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuckHouse.Data.Migrations
{
    [DbContext(typeof(DuckHouseDbContext))]
    partial class DuckHouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuckHouse.Core.Environment.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("DuckHouse.Core.Environment.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("DuckHouse.Core.RuntimePackages.WheelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WheelPackages");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.WorkspaceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceItems_Title_Root")
                        .HasFilter("\"FolderId\" IS NULL");

                    b.HasIndex("Title", "FolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceItems_Title_FolderId")
                        .HasFilter("\"FolderId\" IS NOT NULL");

                    b.ToTable("WorkspaceItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("WorkspaceItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentRuns")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobParameters");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTaskRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ParentRunId");

                    b.HasIndex("Status");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextFireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSchedules");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<TimeSpan>("RetryInterval")
                        .HasColumnType("interval");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeSpan?>("Timeout")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Name")
                        .IsUnique();

                    b.ToTable("JobTasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("JobTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.NodePoolConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentVariableIds")
                        .HasColumnType("jsonb");

                    b.Property<TimeSpan?>("KernelIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<string>("KernelRequirements")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeSpan?>("NodeIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<string>("SecretIds")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VmSize")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WheelPackageIds")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NodePoolConfigs");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("KernelId")
                        .HasColumnType("text");

                    b.Property<string>("NodeName")
                        .HasColumnType("text");

                    b.Property<string>("NotebookOutputJson")
                        .HasColumnType("text");

                    b.Property<string>("QueryResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRunCellOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CellIndex")
                        .HasColumnType("integer");

                    b.Property<string>("CellRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CellSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CellType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ExecutionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OutputsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskRunId", "CellIndex");

                    b.ToTable("TaskRunCellOutputs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.Notebook", b =>
                {
                    b.HasBaseType("DuckHouse.Core.Workspace.WorkspaceItem");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.Query", b =>
                {
                    b.HasBaseType("DuckHouse.Core.Workspace.WorkspaceItem");

                    b.Property<double?>("LastDurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastResultJson")
                        .HasColumnType("text");

                    b.Property<string>("LastResultStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasDiscriminator().HasValue("Query");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.NotebookTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.SqlQueryTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("NodePoolRef")
                                .HasColumnName("SqlQueryTask_NodePoolRef");

                            t.Property("Parameters")
                                .HasColumnName("SqlQueryTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SqlQuery");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.SubJobTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SubJobId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("Parameters")
                                .HasColumnName("SubJobTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SubJob");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.Folder", b =>
                {
                    b.HasOne("DuckHouse.Core.Workspace.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.WorkspaceItem", b =>
                {
                    b.HasOne("DuckHouse.Core.Workspace.Folder", "Folder")
                        .WithMany("Items")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobRun", "ParentRun")
                        .WithMany()
                        .HasForeignKey("ParentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("ParentRun");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Schedules")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobRun", "JobRun")
                        .WithMany("TaskRuns")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRunCellOutput", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.TaskRun", "TaskRun")
                        .WithMany("CellOutputs")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("DuckHouse.Core.Workspace.Folder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Navigation("TaskRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.Navigation("CellOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
