// <auto-generated />
using System;
using DuckHouse.Orchestrator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuckHouse.Orchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(OrchestratorDbContext))]
    [Migration("20260412191351_AddNodePoolWheelPackageIds")]
    partial class AddNodePoolWheelPackageIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentRuns")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobParameters");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTaskRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ParentRunId");

                    b.HasIndex("Status");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextFireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSchedules");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<TimeSpan>("RetryInterval")
                        .HasColumnType("interval");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeSpan?>("Timeout")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobTasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("JobTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.NodePoolConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("KernelIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<string>("KernelRequirements")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeSpan?>("NodeIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VmSize")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WheelPackageIds")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NodePoolConfigs");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("KernelId")
                        .HasColumnType("text");

                    b.Property<string>("NodeName")
                        .HasColumnType("text");

                    b.Property<string>("NotebookOutputJson")
                        .HasColumnType("text");

                    b.Property<string>("QueryResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRunCellOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CellIndex")
                        .HasColumnType("integer");

                    b.Property<string>("CellRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CellSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CellType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ExecutionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OutputsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TaskRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskRunId", "CellIndex");

                    b.ToTable("TaskRunCellOutputs");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.NotebookTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.SqlQueryTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("NodePoolRef")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("NodePoolRef")
                                .HasColumnName("SqlQueryTask_NodePoolRef");

                            t.Property("Parameters")
                                .HasColumnName("SqlQueryTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SqlQuery");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.SubJobTask", b =>
                {
                    b.HasBaseType("DuckHouse.Orchestrator.Core.Entities.JobTask");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SubJobId")
                        .HasColumnType("uuid");

                    b.ToTable("JobTasks", t =>
                        {
                            t.Property("Parameters")
                                .HasColumnName("SubJobTask_Parameters");
                        });

                    b.HasDiscriminator().HasValue("SubJob");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobParameter", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobRun", "ParentRun")
                        .WithMany()
                        .HasForeignKey("ParentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("ParentRun");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobSchedule", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Schedules")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskDependency", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobRun", "JobRun")
                        .WithMany("TaskRuns")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.JobTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRunCellOutput", b =>
                {
                    b.HasOne("DuckHouse.Orchestrator.Core.Entities.TaskRun", "TaskRun")
                        .WithMany("CellOutputs")
                        .HasForeignKey("TaskRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.Job", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobRun", b =>
                {
                    b.Navigation("TaskRuns");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.JobTask", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("DuckHouse.Orchestrator.Core.Entities.TaskRun", b =>
                {
                    b.Navigation("CellOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
