// <auto-generated />
using System;
using DuckHouse.ControlPlane.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuckHouse.ControlPlane.Infrastructure.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    partial class ControlPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuckHouse.ControlPlane.Core.Nodes.NodeConfig", b =>
                {
                    b.Property<string>("NodeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<TimeSpan>("KernelIdleTimeout")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("NodeIdleTimeout")
                        .HasColumnType("interval");

                    b.HasKey("NodeName");

                    b.ToTable("NodeConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
