// <auto-generated />
using System;
using DuckHouse.Ui.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuckHouse.Ui.Server.Infrastructure.Migrations
{
    [DbContext(typeof(UiDbContext))]
    [Migration("20260412191336_AddWheelPackages")]
    partial class AddWheelPackages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Packages.WheelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WheelPackages");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.WorkspaceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("WorkspaceItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("WorkspaceItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.Notebook", b =>
                {
                    b.HasBaseType("DuckHouse.Ui.Server.Core.Workspace.WorkspaceItem");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.Query", b =>
                {
                    b.HasBaseType("DuckHouse.Ui.Server.Core.Workspace.WorkspaceItem");

                    b.Property<double?>("LastDurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastResultJson")
                        .HasColumnType("text");

                    b.Property<string>("LastResultStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasDiscriminator().HasValue("Query");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.Folder", b =>
                {
                    b.HasOne("DuckHouse.Ui.Server.Core.Workspace.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.WorkspaceItem", b =>
                {
                    b.HasOne("DuckHouse.Ui.Server.Core.Workspace.Folder", "Folder")
                        .WithMany("Items")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("DuckHouse.Ui.Server.Core.Workspace.Folder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
